#!/bin/sh
RED='\033[1;31m'
GREEN='\033[1;32m'

if npm run test:cover
then
    echo "${GREEN}SUCCESS : Code coverage fulfill."
    exit 0;
else 
    echo "${RED}ERROR : Code coverage not fulfill."
    exit 1;
fi 